version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: pp_password
      MYSQL_DATABASE: pp_db
      MYSQL_USER: pp_user
      MYSQL_PASSWORD: pp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
